version: "3"
services:
  bitcoin-core-test3:
    image: ruimarinho/bitcoin-core
    ports:
      - "18332:18332"
      - "18333:18333"
    volumes:
      - btc_test3_data:/home/bitcoin/.bitcoin
    command:
      -printtoconsole
      -regtest=1
