version: "3"
services:
  esplora-test3:
    image: blockstream/esplora

    ports:
      - "8084:80"
    volumes:
      - ./btc_test3_data:/data
    command: >
      bash -c "/srv/explorer/run.sh bitcoin-testnet explorer"

  #bitcoin-core-test3:
  #  image: ruimarinho/bitcoin-core
  #  ports:
  #    - "18332:18332"
  #    - "18333:18333"
  #  volumes:
  #    - ./btc_test3_data:/home/bitcoin/.bitcoin
  #  command:
  #    -printtoconsole
  #    -regtest=1
      
